var DataOcean=DataOcean||{};
DataOcean.Bluewhale={bwTrck:{VIEW_TIMER:function(){},VIEW_TIMEOUT:1E3,BASE_DOMAIN:"https:"===document.location.protocol?"https://squid.gazeta.pl":"http://squid.gazeta.pl",USER_EVENT_URL:"",BLUEWHALE_IFRAME_URL:"",BLUEWHALE_IFRAME_ID:"bluewhaleIframe",BLUEWHALE_IFRAME:{},PAGE_VIEW_ID:"",VISIT_ID:"",BLUEWHALE_GUID:"",BLUEWHALE_GUID_COOKIE_NAME:"bwGuidv2",TEMPLATE_URL:"",PIXELS:[],MONITORING_INITIATED:!1,monitoringSettings:{},userEventCache:[],CACHE_USER_EVENTS:!0,CUSTOM_EVENTS:{},init:function(){this.USER_EVENT_URL=
this.BASE_DOMAIN+"/bdtrck/updDcUe";this.BLUEWHALE_IFRAME_URL=this.BASE_DOMAIN+"/bdtrck/getBdIf";var b=DataOcean.Bluewhale.bwTrck,a=b.BLUEWHALE_IFRAME_URL,c=window.location.hostname||"null",d=window.location||"null",e=b.getCookieValue("SquidLocalUID")||"",g=document.referrer||"",f="",h="",j="",k=b.getCookieValue("UserID")||"",l=b.getCookieValue(this.BLUEWHALE_GUID_COOKIE_NAME);"undefined"!==typeof banCookie&&(j=banCookie.substring(20,banCookie.length-7));"undefined"!==typeof pw_application&&pw_application.user&&
(pw_application.user.CID&&(f="_"===pw_application.user.CID?"":pw_application.user.CID),pw_application.user.Access&&(h=pw_application.user.Access));a=b.prepareUrl(a,{domain:c,visitedUrl:d,referer:g,luid:e,pianocid:f,pianoaccess:h,adservercid:j,portallogin:k,bluewhaleguid:l,rnd:(""+Math.random()).substring(3)});c=function(a){var c=a.origin||a.originalEvent.origin;a=a.data||a.originalEvent.data;if(c&&c===DataOcean.Bluewhale.bwTrck.BASE_DOMAIN&&a&&-1<a.indexOf("IFRAMELOADED")&&b.CACHE_USER_EVENTS){c=
{};try{c=JSON.parse(a)}catch(d){}b.PAGE_VIEW_ID=c.pageviewid||"";b.VISIT_ID=c.visitid||"";b.BLUEWHALE_GUID=c.guid||"";b.TEMPLATE_URL=c.templateurl||"";b.PIXELS=c.pixels||[];b.setCookie("bwGuid",b.BLUEWHALE_GUID,8760,"/");b.getMonitoringSettings();b.getPixels(b.PIXELS)}};this.jqueryEnabled()&&$(window).bind?$(window).bind("message",c):window.addEventListener?window.addEventListener("message",c,!1):window.attachEvent&&window.attachEvent("onmessage",c);b.createIframe(a,b.BLUEWHALE_IFRAME_ID);b.BLUEWHALE_IFRAME=
this.jqueryEnabled()&&$("#"+b.BLUEWHALE_IFRAME_ID)&&$("#"+b.BLUEWHALE_IFRAME_ID)[0]?$("#"+b.BLUEWHALE_IFRAME_ID)[0]:document.getElementById(b.BLUEWHALE_IFRAME_ID)},jqueryEnabled:function(){return"undefined"!==typeof $},getMonitoringSettings:function(){var b=this.getSettingsUrl();if(this.jqueryEnabled()&&$.getScript)$.getScript(b);else{var a=document.createElement("script");a.async=!0;a.src=b;document.head.appendChild(a)}},getSettingsUrl:function(){var b;b=DataOcean.Bluewhale.bwTrck.TEMPLATE_URL&&
""!==DataOcean.Bluewhale.bwTrck.TEMPLATE_URL?DataOcean.Bluewhale.bwTrck.TEMPLATE_URL:"http://bi.gazeta.pl/info/bluewhale/tmpl/undefined.js";"https:"===document.location.protocol&&(b=b.replace(/http:\/\/.+?\//,"https://squid.gazeta.pl/"));return b},getPixels:function(b){for(var a=0;a<b.length;a++)try{(new Image(1,1)).src=b[a]}catch(c){}},initMonitoring:function(b){if(!this.MONITORING_INITIATED){this.CUSTOM_EVENTS={view:this.createCustomEvent("view"),hide:this.createCustomEvent("hide")};this.monitoringSettings=
b;this.monitoringSettings.view=[];if(this.monitoringSettings&&this.monitoringSettings.events&&0<this.monitoringSettings.events.length){this.setViewEventListeners();for(var a=0;a<this.monitoringSettings.events.length;a++){var c=b.events[a];this.setUserEventListener(c.dict_event_id,c.selector,c.event_name,c.handler,c.attributes);("view"===c.event_name||"hide"===c.event_name)&&this.monitoringSettings.view.push(c.selector)}}this.MONITORING_INITIATED=!0;this.CACHE_USER_EVENTS=!1;this.processUserEventCache()}},
createCustomEvent:function(b){var a;document.createEvent?(a=document.createEvent("HTMLEvents"),a.initEvent(b,!0,!0)):(a=document.createEventObject(),a.eventType=b);a.eventName=b;return a},fireCustomEvent:function(b,a){if(this.jqueryEnabled()&&$(a).trigger)$(a).trigger(b);else{var c=DataOcean.Bluewhale.bwTrck.CUSTOM_EVENTS[b];document.createEvent?a.dispatchEvent(c):a.fireEvent("on"+c.eventType,c)}},processUserEventCache:function(){for(;0!==this.userEventCache.length;){var b=this.userEventCache.shift();
this.logUserEvent(b.dict_event_id,b.object_id,b.local_timestamp,b.attr)}},prepareUrl:function(b,a){var c="",d;for(d in a)""!==a[d]&&(c+=encodeURIComponent(d)+"="+encodeURIComponent(a[d])+"&");return b+"?"+c},createIframe:function(b,a){if(this.jqueryEnabled())return $("BODY").append('<iframe async="" id="'+a+'" style="position:absolute;left:-9999px;top:0;width:1px;height:1px;" src="'+b+'"></iframe>');this.attachIframe(b,a)},getCookieValue:function(b){b+="=";for(var a=document.cookie.split(";"),c=0;c<
a.length;c++){for(var d=a[c];" "===d.charAt(0);)d=d.substring(1,d.length);if(0===d.indexOf(b))return unescape(d.substring(b.length,d.length))}return null},setCookie:function(b,a,c,d,e,g){var f=(new Date).getTime();c&&(c*=36E5);f=new Date(f+c);document.cookie=b+"="+escape(a)+(c?";expires="+f.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(g?";secure":"")},attachIframe:function(b,a){var c=document.createElement("iframe");c.setAttribute("style","position:absolute;left:-9999px;top:0;width:1px;height:1px;");
c.id=a;c.src=b;try{document.body.appendChild(c)}catch(d){var e=function(){document.body.appendChild(c)};window.addEventListener?window.addEventListener("load",e,!1):window.attachEvent&&window.attachEvent("onload",e)}return c},setViewEventListeners:function(){this.jqueryEnabled()&&$(window).bind?$(window).bind("DOMContentLoaded load resize scroll click",this.onView):window.addEventListener?(addEventListener("DOMContentLoaded",this.onView,!1),addEventListener("load",this.onView,!1),addEventListener("scroll",
this.onView,!1),addEventListener("resize",this.onView,!1),addEventListener("click",this.onView,!1)):window.attachEvent&&(attachEvent("onDOMContentLoaded",this.onView),attachEvent("onload",this.onView),attachEvent("onscroll",this.onView),attachEvent("onresize",this.onView),attachEvent("onclick",this.onView));this.jqueryEnabled()&&$(document).bind?$(document).bind("visibilitychange",this.onView):document.addEventListener?document.addEventListener("visibilitychange",this.onView,!1):window.attachEvent&&
document.attachEvent("onvisibilitychange",this.onView)},setUserEventListener:function(b,a,c,d,e){e=e||[];if($(window).bind)$(a).bind(c,function(c){DataOcean.Bluewhale.bwTrck[d](c,b,a,e)});else{var g=$(a);if(window.addEventListener)for(var f=0;f<g.length;f++)g[f].addEventListener(c,function(c){DataOcean.Bluewhale.bwTrck[d](c,b,a,e)},!1);else if(window.attachEvent)for(f=0;f<g.length;f++)g[f].attachEvent("on"+c,function(c){DataOcean.Bluewhale.bwTrck[d](c,b,a,e)})}},isElementVisible:function(b){b instanceof
jQuery&&(b=b[0]);var a=b.getBoundingClientRect(),c=window.innerHeight||document.documentElement.clientHeight,d=window.innerWidth||document.documentElement.clientWidth,e=a.left+a.width/2,g=a.top+a.height/2;return a.height<c&&a.width<d?0>a.top||0>a.left||a.bottom>c||a.right>d?!1:DataOcean.Bluewhale.bwTrck.isElementNotCovered(b,e,g):a.top<c/2&&a.bottom>c/2&&0<=a.left&&a.right<=d?(g=Math.max(0,a.top)+(Math.min(c,a.bottom)-Math.max(0,a.top))/2,DataOcean.Bluewhale.bwTrck.isElementNotCovered(b,e,g)):a.left<
d/2&&a.right>d/2&&0<=a.top&&a.bottom<=c?(e=Math.max(0,a.left)+(Math.min(d,a.right)-Math.max(0,a.left))/2,DataOcean.Bluewhale.bwTrck.isElementNotCovered(b,e,g)):!1},isElementNotCovered:function(b,a,c){var d,e="contains"in b?"contains":"compareDocumentPosition",g="contains"==e?1:20;return(d=document.elementFromPoint(a,c))==b||b[e](d)==g||d[e](b)==g},onView:function(){if(document.visibilityState&&"visible"===document.visibilityState||!document.visibilityState)window.clearTimeout(DataOcean.Bluewhale.bwTrck.VIEW_TIMER),
DataOcean.Bluewhale.bwTrck.VIEW_TIMER=setTimeout(function(){DataOcean.Bluewhale.bwTrck.checkViewEvents()},DataOcean.Bluewhale.bwTrck.VIEW_TIMEOUT)},onEvent:function(b,a,c,d){d=DataOcean.Bluewhale.bwTrck.getMonitoredAttributes(b.currentTarget||b.target,d);DataOcean.Bluewhale.bwTrck.logUserEvent(a,c,b.timeStamp,d)},checkViewEvents:function(){for(var b=DataOcean.Bluewhale.bwTrck.monitoringSettings,a=0;a<b.view.length;a++)for(var c=$(b.view[a]),d=0;d<c.length;d++){var e=c[d],g=DataOcean.Bluewhale.bwTrck.isElementVisible(e);
if((e.isVisible||0)^g)DataOcean.Bluewhale.bwTrck.fireCustomEvent(g?"view":"hide",e),e.isVisible=g}},getMonitoredAttributes:function(b,a){retAttrs={};for(var c=0;c<a.length;c++){var d;d="function"===typeof a[c].object?a[c].object(b):b;d="function"===typeof a[c].attribute?a[c].attribute(d):d.getAttribute(a[c].attribute);retAttrs[a[c].name]=d}return retAttrs},logUserEvent:function(b,a,c,d){try{var e=DataOcean.Bluewhale.bwTrck;if(e.CACHE_USER_EVENTS){f={};f.dict_event_id=b;f.object_id=a;f.local_timestamp=
c;f.attr=d;try{e.userEventCache.push(f)}catch(g){}}else{var f=d||{};f.dict_event_id=b;f.object_id=a;f.local_timestamp=c;f.url=window.location.href;f.pageview_id=e.PAGE_VIEW_ID||"";f.visit_id=e.VISIT_ID||"";f.guid=e.BLUEWHALE_GUID||"";var h=JSON.stringify(f);e.BLUEWHALE_IFRAME.contentWindow.postMessage(h,"*")}}catch(j){}}}};setTimeout(function(){try{DataOcean.Bluewhale.bwTrck.init()}catch(b){}},20);var bwTestVarXY=!0;
