var gazeta_pl=gazeta_pl||{};
gazeta_pl.Bluewhale={bwTrck:{VIEW_TIMER:function(){},VIEW_TIMEOUT:1E3,BASE_DOMAIN:"http://squid.gazeta.pl",USER_EVENT_URL:"",BLUEWHALE_IFRAME_URL:"",BLUEWHALE_IFRAME_ID:"bluewhaleIframe",BLUEWHALE_IFRAME:{},PAGE_VIEW_ID:"",VISIT_ID:"",BLUEWHALE_GUID:"",BLUEWHALE_GUID_COOKIE_NAME:"bwGuid",TEMPLATE_URL:"",monitoringSettings:{},userEventCache:[],CACHE_USER_EVENTS:!0,CUSTOM_EVENTS:{},init:function(){this.USER_EVENT_URL=this.BASE_DOMAIN+"/bdtrck/updDcUe";this.BLUEWHALE_IFRAME_URL=this.BASE_DOMAIN+"/bdtrck/getBdIf";
var c=gazeta_pl.Bluewhale.bwTrck,a=c.BLUEWHALE_IFRAME_URL,b=window.location.hostname||"null",d=window.location||"null",e=c.getCookieValue("SquidLocalUID")||"",g=document.referrer||"",f="",h="",j=c.getCookieValue("UserID")||"",k=c.getCookieValue(this.BLUEWHALE_GUID_COOKIE_NAME);"undefined"!==typeof banCookie&&(h=banCookie.substring(20,banCookie.length-7));"undefined"!==typeof pw_application&&(pw_application.user&&pw_application.user.CID)&&(f="_"===pw_application.user.CID?"":pw_application.user.CID);
a=c.prepareUrl(a,{domain:b,visitedUrl:d,referer:g,luid:e,pianocid:f,adservercid:h,portallogin:j,bluewhaleguid:k,rnd:(""+Math.random()).substring(3)});b=function(a){var b=a.origin||a.originalEvent.origin;a=a.data||a.originalEvent.data;if(b&&b===gazeta_pl.Bluewhale.bwTrck.BASE_DOMAIN&&a&&-1<a.indexOf("IFRAMELOADED")){b={};try{b=JSON.parse(a)}catch(d){}c.PAGE_VIEW_ID=b.pageviewid||"";c.VISIT_ID=b.visitid||"";c.BLUEWHALE_GUID=b.guid||"";c.TEMPLATE_URL=b.templateurl||"";c.setCookie("bwGuid",c.BLUEWHALE_GUID,
8760,"/");c.getMonitoringSettings()}};this.jqueryEnabled()&&$(window).bind?$(window).bind("message",b):window.addEventListener?window.addEventListener("message",b,!1):window.attachEvent&&window.attachEvent("onmessage",b);c.createIframe(a,c.BLUEWHALE_IFRAME_ID);c.BLUEWHALE_IFRAME=this.jqueryEnabled()&&$("#"+c.BLUEWHALE_IFRAME_ID)&&$("#"+c.BLUEWHALE_IFRAME_ID)[0]?$("#"+c.BLUEWHALE_IFRAME_ID)[0]:document.getElementById(c.BLUEWHALE_IFRAME_ID)},jqueryEnabled:function(){return"undefined"!==typeof $},getMonitoringSettings:function(){var c=
this.getSettingsUrl();if(this.jqueryEnabled()&&$.getScript)$.getScript(c);else{var a=document.createElement("script");a.src=c;document.head.appendChild(a)}},getSettingsUrl:function(){return gazeta_pl.Bluewhale.bwTrck.TEMPLATE_URL&&""!==gazeta_pl.Bluewhale.bwTrck.TEMPLATE_URL?gazeta_pl.Bluewhale.bwTrck.TEMPLATE_URL:"http://biv.gazeta.pl/info/bluewhale/tmpl/undefined.js"},initMonitoring:function(c){this.CUSTOM_EVENTS={view:this.createCustomEvent("view"),hide:this.createCustomEvent("hide")};if((this.monitoringSettings=
c)&&this.monitoringSettings.events&&0<this.monitoringSettings.events.length){this.setViewEventListeners();this.monitoringSettings.view=[];for(var a=0;a<this.monitoringSettings.events.length;a++){var b=c.events[a];this.setUserEventListener(b.dict_event_id,b.selector,b.event_name,b.handler,b.attributes);("view"===b.event_name||"hide"===b.event_name)&&this.monitoringSettings.view.push(b.selector)}}this.CACHE_USER_EVENTS=!1;this.processUserEventCache()},createCustomEvent:function(c){var a;document.createEvent?
(a=document.createEvent("HTMLEvents"),a.initEvent(c,!0,!0)):(a=document.createEventObject(),a.eventType=c);a.eventName=c;return a},fireCustomEvent:function(c,a){if(this.jqueryEnabled()&&$(a).trigger)$(a).trigger(c);else{var b=gazeta_pl.Bluewhale.bwTrck.CUSTOM_EVENTS[c];document.createEvent?a.dispatchEvent(b):a.fireEvent("on"+b.eventType,b)}},processUserEventCache:function(){for(;0!==this.userEventCache.length;){var c=this.userEventCache.shift();this.logUserEvent(c.dict_event_id,c.object_id,c.local_timestamp,
c.attr)}},prepareUrl:function(c,a){var b="",d;for(d in a)""!==a[d]&&(b+=encodeURIComponent(d)+"="+encodeURIComponent(a[d])+"&");return c+"?"+b},createIframe:function(c,a){if(this.jqueryEnabled())return $("BODY").append('<iframe async="" id="'+a+'" style="position:absolute;left:-9999px;top:0;width:1px;height:1px;" src="'+c+'"></iframe>');this.attachIframe(c,a)},getCookieValue:function(c){c+="=";for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var d=a[b];" "===d.charAt(0);)d=d.substring(1,
d.length);if(0===d.indexOf(c))return unescape(d.substring(c.length,d.length))}return null},setCookie:function(c,a,b,d,e,g){var f=(new Date).getTime();b&&(b*=36E5);f=new Date(f+b);document.cookie=c+"="+escape(a)+(b?";expires="+f.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(g?";secure":"")},attachIframe:function(c,a){var b=document.createElement("iframe");b.setAttribute("style","position:absolute;left:-9999px;top:0;width:1px;height:1px;");b.id=a;b.src=c;document.body.appendChild(b);return b},
setViewEventListeners:function(){this.jqueryEnabled()&&$(window).bind?$(window).bind("DOMContentLoaded load resize scroll click",this.onView):window.addEventListener?(addEventListener("DOMContentLoaded",this.onView,!1),addEventListener("load",this.onView,!1),addEventListener("scroll",this.onView,!1),addEventListener("resize",this.onView,!1),addEventListener("click",this.onView,!1)):window.attachEvent&&(attachEvent("onDOMContentLoaded",this.onView),attachEvent("onload",this.onView),attachEvent("onscroll",
this.onView),attachEvent("onresize",this.onView),attachEvent("onclick",this.onView));this.jqueryEnabled()&&$(document).bind?$(document).bind("visibilitychange",this.onView):document.addEventListener?document.addEventListener("visibilitychange",this.onView,!1):window.attachEvent&&document.attachEvent("onvisibilitychange",this.onView)},setUserEventListener:function(c,a,b,d,e){e=e||[];if($(window).live)$(a).live(b,function(b){gazeta_pl.Bluewhale.bwTrck[d](b,c,a,e)});else{var g=$(a);if(window.addEventListener)for(var f=
0;f<g.length;f++)g[f].addEventListener(b,function(b){gazeta_pl.Bluewhale.bwTrck[d](b,c,a,e)},!1);else if(window.attachEvent)for(f=0;f<g.length;f++)g[f].attachEvent("on"+b,function(b){gazeta_pl.Bluewhale.bwTrck[d](b,c,a,e)})}},isElementVisible:function(c){c instanceof jQuery&&(c=c[0]);var a=c.getBoundingClientRect(),b=window.innerHeight||document.documentElement.clientHeight,d=window.innerWidth||document.documentElement.clientWidth,e=a.left+a.width/2,g=a.top+a.height/2;return a.height<b&&a.width<d?
0>a.top||0>a.left||a.bottom>b||a.right>d?!1:gazeta_pl.Bluewhale.bwTrck.isElementNotCovered(c,e,g):a.top<b/2&&a.bottom>b/2&&0<=a.left&&a.right<=d?(g=Math.max(0,a.top)+(Math.min(b,a.bottom)-Math.max(0,a.top))/2,gazeta_pl.Bluewhale.bwTrck.isElementNotCovered(c,e,g)):a.left<d/2&&a.right>d/2&&0<=a.top&&a.bottom<=b?(e=Math.max(0,a.left)+(Math.min(d,a.right)-Math.max(0,a.left))/2,gazeta_pl.Bluewhale.bwTrck.isElementNotCovered(c,e,g)):!1},isElementNotCovered:function(c,a,b){var d,e="contains"in c?"contains":
"compareDocumentPosition",g="contains"==e?1:20;return(d=document.elementFromPoint(a,b))==c||c[e](d)==g||d[e](c)==g},onView:function(){if(document.visibilityState&&"visible"===document.visibilityState||!document.visibilityState)window.clearTimeout(gazeta_pl.Bluewhale.bwTrck.VIEW_TIMER),gazeta_pl.Bluewhale.bwTrck.VIEW_TIMER=setTimeout(function(){gazeta_pl.Bluewhale.bwTrck.checkViewEvents()},gazeta_pl.Bluewhale.bwTrck.VIEW_TIMEOUT)},onEvent:function(c,a,b,d){d=gazeta_pl.Bluewhale.bwTrck.getMonitoredAttributes(c.target,
d);gazeta_pl.Bluewhale.bwTrck.logUserEvent(a,b,c.timeStamp,d)},checkViewEvents:function(){for(var c=gazeta_pl.Bluewhale.bwTrck.monitoringSettings,a=0;a<c.view.length;a++)for(var b=$(c.view[a]),d=0;d<b.length;d++){var e=b[d],g=gazeta_pl.Bluewhale.bwTrck.isElementVisible(e);if((e.isVisible||0)^g)gazeta_pl.Bluewhale.bwTrck.fireCustomEvent(g?"view":"hide",e),e.isVisible=g}},getMonitoredAttributes:function(c,a){retAttrs={};for(var b=0;b<a.length;b++){var d;d="function"===typeof a[b].object?a[b].object(c):
c;d="function"===typeof a[b].attribute?a[b].attribute(d):d.getAttribute(a[b].attribute);retAttrs[a[b].name]=d}return retAttrs},logUserEvent:function(c,a,b,d){try{var e=gazeta_pl.Bluewhale.bwTrck;if(e.CACHE_USER_EVENTS){f={};f.dict_event_id=c;f.object_id=a;f.local_timestamp=b;f.attr=d;try{e.userEventCache.push(f)}catch(g){}}else{var f=d;f.dict_event_id=c;f.object_id=a;f.local_timestamp=b;f.url=window.location.href;f.pageview_id=e.PAGE_VIEW_ID||"";f.visit_id=e.VISIT_ID||"";f.guid=e.BLUEWHALE_GUID||
"";var h=JSON.stringify(f);e.BLUEWHALE_IFRAME.contentWindow.postMessage(h,"*")}}catch(j){}}}};setTimeout(function(){gazeta_pl.Bluewhale.bwTrck.init()},20);
